package fgroupindonesia.printscreen;

import java.awt.Container;
import java.io.File;
import javax.swing.JFrame;

/*
 * System : JavaPrintScreen
 * Description : 
 * This file is the main frame used as a canvas (transparent)
 * for DrawSketch to make a rectangular object while snipping..
 *
 */
public class MainArea extends javax.swing.JFrame {

    public MainArea(ScreenshotTaker sctaker) {
        initComponents();
        
        this.setScreenshotTaker(sctaker);
        start();

        if (EngineStates.logo_visibility) {

            if (EngineStates.logo_absolute_path != null) {
                // we use the user picture
                if (EngineStates.logo_absolute_path.exists()) {
                    showCustomTooltip();
                } else {
                    showDefaultTooltip();
                }
            } else {
                // we use the default one
                showDefaultTooltip();
            }

        }
    }

    DrawSketch drawS = null;
    ScreenshotTaker staker = null;

    public void setScreenshotTaker(ScreenshotTaker sctaker){
        staker = sctaker;
    }
    
    public void start() {
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        if (drawS == null) {
            drawS = new DrawSketch(this, staker);
            Container cPane = this.getContentPane();
            cPane.add(drawS);
        } else {
            drawS.clearAll();
        }

        setOpacity(0.4f);
    }

    TrayIconMaker trayna;

    String lokasiImage = DefaultPath.systemLocation + File.separator + "logo.png";

    public void showCustomTooltip() {
        trayna = new TrayIconMaker(EngineStates.logo_absolute_path, this);
    }

    public void showDefaultTooltip() {
        trayna = new TrayIconMaker(new File(lokasiImage), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // dont run on this file
                // new MainArea(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
